backend:
  name: git-gateway
  branch: master
media_folder: src/images
public_folder: public
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }